config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show] do
    resources :ideas
  end

  namespace :admin do
    resources :categories
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :ideas
  validates :username, uniqueness: true
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  before_action :require_admin

  def require_admin
    render file: '/public/404' unless current_admin?
  end

end

app/controllers/admin/categories_controller.rb
class CategoriesController < Admin::BaseController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  def index
    @ideas = Idea.all
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new(idea_params)
    @user = User.find(params[:user_id])
    if @idea.save
      @idea.update(user_id: @user.id)
      flash[:notice] = 'Idea Created!'
      redirect_to user_ideas_path(current_user)
    else
      flash.now[:error] = @idea.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
    @idea = Idea.find(params[:id])
    if @idea.user != current_user
      redirect_to login_path
    end
  end

  def edit
    @idea = Idea.find(params[:id])
    if @idea.user != current_user
      redirect_to login_path
    end
  end

  def update
    @idea = Idea.find(params[:id])
    if @idea.update_attributes(idea_params)
      redirect_to user_idea_path(current_user, @idea.id)
    else
      render :edit
    end
  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    redirect_to user_ideas_path(current_user)
  end

  private

  def idea_params
    params.require(:idea).permit(:name, :description)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_ideas_path(@user)
    else
      flash.now[:alert] = "Invalid username and/or password"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to login_path
    flash[:notice] = "Goodbye"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_ideas_path(@user)
    else
      flash.now[:error] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
    if current_user != user_path
      redirect_to new_user_path, alert: "Unauthorized"
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ideas/_form.html.erb
<%= form_for [current_user, @idea] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>&nbsp

  <%= f.label :description %>
  <%= f.text_field :description %> &nbsp &nbsp

  <%= f.submit class: "btn btn-success btn-sm", method: :post %>

<% end %><br>

app/views/ideas/edit.html.erb
<%= render partial: "form" %>
<%= link_to "Cancel", user_idea_path(current_user, @idea.id), class: "btn btn-primary btn-sm", method: :get %>

app/views/ideas/index.html.erb
<% current_user.ideas.each do |idea| %>
  <%= link_to idea.name, user_idea_path(current_user, idea.id) %>
  <br><br>
<% end %>
<br>

<%= link_to "Create Idea", new_user_idea_path(current_user), class: "btn btn-primary btn-sm" %>

app/views/ideas/new.html.erb
<%= render partial: "form" %>
<%= button_to "Cancel", user_ideas_path(current_user), class: "btn btn-primary btn-sm", method: :get %>

app/views/ideas/show.html.erb
<h3><%= @idea.name  %></h3>
Description: <%= @idea.description %><br><br>

<%= button_to "Edit", edit_user_idea_path(current_user, @idea.id), class: "btn btn-primary btn-sm", method: :get %><br>
<%= button_to "Delete", user_idea_path(current_user, @idea.id), class: "btn btn-danger btn-sm", method: :delete %><br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <link rel="stylesheet" href="/css/bootstrap.min.css">
  <link rel="stylesheet" href="/css/application.css">
  <title>Ideabox</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="user_bar">
    <% if current_user %>
    <h2> Welcome, <%= current_user.username %></h2>
    <%= button_to "Logout", logout_path, class: "btn btn-warning btn-xs", method: :delete %><br>
    <%= button_to "Home", user_ideas_path(current_user), class: "btn btn-success btn-xs", method: :get %><br>
    <% end %>
  </div>
  <% flash.each do |type, msg| %>
  <%= content_tag :div, msg, class: "flash_#{type}" %>
  <% end %>

  <%= yield %>
</body>
</html>

app/views/users/new.html.erb
<h1>Create a new account</h1>

<%= form_for(@user) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br><br>

  <%= f.label :password %>
  <%= f.password_field :password %><br><br>

  <%= f.submit "Create Account", class: "btn btn-success btn-sm", method: :post %>
  <% end %>

app/views/users/show.html.erb
<h1>User show page</h1>